### PR TITLE
Summary: Fix issue #48

### PR DESCRIPTION
**Pull request by leowmjw**
Changesets:
- Detect typeof "number" for token; applying toString() as needed

### CODE REVIEW

**Comment by pwalsh** [comment]
@kravets-levko can you please review / merge this?

**Comment by kravets-levko** [comment]
@pwalsh I reviewed code, it looks well, but I have no write access to merge it.

**Comment by pwalsh** [comment]
@kravets-levko you have admin access now.

**Comment by leowmjw** [comment]
@kravets-levko Please help update the /dist generated by this PR; it seems the code dependency on this repo does not causes it to re-generate the contents in /dist.  Thanks!

**Comment by kravets-levko** [comment]
@leowmjw I updated `/dist` and increased build number, and asked to publish this to npm (I have no permissions). Will notify you when ready.

**Pull request merged**
